name: arxiv-daily

permissions:
  contents: read          # 默认就有的
  actions: read           # 允许读变量/密钥元数据
  secrets: read           # 显式声明读 secret
  
on:
  schedule:
    - cron: "0 1 * * *"   # 每天 01:00 UTC 运行（新加坡时间约 09:00）
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tracker
        run: |
          python -m arxiv_tracker.cli run --config config.yaml --out-dir outputs
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arxiv-results
          path: outputs/**
      - name: 检查 GitHub 到底认不认这些变量
        run: |
          gh api -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/variables/EMAIL_TO \
            --jq '.name + "=" + .value' || echo "❌ 仓库级变量 EMAIL_TO 不存在"
          gh api -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/secrets/OPENAI_COMPAT_API_KEY \
            --jq '.name + " exists"' || echo "❌ 仓库级密钥 OPENAI_COMPAT_API_KEY 不存在"
        env:
          GH_TOKEN: ${{ github.token }}
